prometheus:
  url: http://prometheus-server.monitoring.svc
  port: 80
  path: ""

rules:
  default: false

  custom:
    - seriesQuery: 'http_requests_total{job="scaletestapp"}'
      resources:
        overrides:
          namespace:
            resource: namespace
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: |
        sum(rate(<<.Series>>[1m]))
